
# Use new container infrastructure to enable caching
sudo: false

# Do not choose a language; we provide our own build tools.
language: generic

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal
  - $HOME/.stack
  - $HOME/.local/bin
  - $TRAVIS_BUILD_DIR/.stack-work
  - $TRAVIS_BUILD_DIR/submodules/brittany/.stack-work
  - $TRAVIS_BUILD_DIR/submodules/HaRe/.stack-work
  - $TRAVIS_BUILD_DIR/submodules/ghc-mod/.stack-work
  - $TRAVIS_BUILD_DIR/submodules/ghc-mod/core/.stack-work
  - $TRAVIS_BUILD_DIR/submodules/haskell-lsp/.stack-work
  - $TRAVIS_BUILD_DIR/submodules/haskell-lsp/haskell-lsp-types/.stack-work
  - $TRAVIS_BUILD_DIR/submodules/cabal-helper/.stack-work
  - $TRAVIS_BUILD_DIR/hie-plugin-api/.stack-work
  timeout: 800
before_cache:
  - rm -rf $TRAVIS_BUILD_DIR/.stack-work/logs/

matrix:
  include:
  # Stack builds. Can pass in arbitrary Stack arguments via the ARGS
  # variable, such as using --stack-yaml to point to a different file.
# use this one for github release
  - env: BUILD=stack RELEASE="true" GHC_VER="8.4.4" 
    compiler: ": #stack ghc-8.4.4"
    addons: {apt: {packages: [libgmp-dev, libicu-dev, libtinfo-dev], sources: [hvr-ghc]}}



before_install:
# Using compiler above sets CC to an invalid value, so unset it
- unset CC
# Download and unpack the stack executable
- export PATH=/opt/ghc/$GHC_VER/bin:/opt/cabal/$CABALVER/bin:$HOME/.local/bin:/opt/alex/$ALEXVER/bin:/opt/happy/$HAPPYVER/bin:$HOME/.cabal/bin:$PATH
- mkdir -p ~/.local/bin
- |
  export LINUX64_STACK="https://github.com/commercialhaskell/stack/releases/download/v1.7.1/stack-1.7.1-linux-x86_64.tar.gz"
  travis_retry curl -L "${LINUX64_STACK}" | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  rm -rf /home/travis/.stack/setup-exe-cache/
  stack setup $GHC_VER

  # Use the more reliable S3 mirror of Hackage
  mkdir -p $HOME/.cabal
  echo 'remote-repo: hackage.haskell.org:http://hackage.fpcomplete.com/' > $HOME/.cabal/config
  echo 'remote-repo-cache: $HOME/.cabal/packages' >> $HOME/.cabal/config

  if [ "$CABALVER" != "1.16" ]
  then
    echo 'jobs: $ncpus' >> $HOME/.cabal/config
  fi
- stack --version


install:
- |
  set -ex
  case "$BUILD" in
    stack)
      stack --version
      make submodules
      make cabal
      stack --stack-yaml="stack-${GHC_VER}.yaml" install happy
      ;;
    cabal)
      echo NOT DOING CABAL
      ;;
  esac
  set +ex


script:
- |
  set -ex
  case "$BUILD" in
    stack)
      stack --stack-yaml="stack-${GHC_VER}.yaml" build lens aeson blaze-builder  blaze-markup haskell-lexer cryptonite microlens megaparsec attoparsec microlens-th utility-ht
      stack --stack-yaml="stack-${GHC_VER}.yaml" build --dependencies-only
      stack --stack-yaml="stack-${GHC_VER}.yaml" build
      echo make hie-8.4.4
      echo make build-doc-8.4.4
      ;;
  esac
  set +ex

#before_deploy:
#- PKGVER=$(cabal info . | head -n  1 | cut -d ' ' -f 2)
#- SRC_TGZ=$PKGVER.tar.gz
#- |
#  if [ ! -f "$SRC_TGZ" ] ; then
#    stack sdist;
#    distdir=`stack path --dist-dir`; 
#    cp $distdir/$SRC_TGZ .;
#  fi
#- ls -al "$SRC_TGZ"; true
#- cp ~/.local/bin/hup .
#- tar cf hup_x86_64.tgz --gzip hup
#- ls -al hup_x86_64.tgz
#
#
#deploy:
#  provider: releases
#  file: 
#  - "$SRC_TGZ"
#  - hup_x86_64.tgz
#  skip_cleanup: true
#  # overwrite: true
#  api_key:
#    secure: RzlHVrVLGvb8Or+PLzfdUF6YFIFU65xqZ3hl8TodglRnA8avcfej/W/K/aaXKb+i9eL4lmbc8WtTR5Qm8CxNtlR/uPAC1LBEVhJQHBKn6n1/uRTMOaRs75UjsIcm3GQKuOWI0HpMvb8Px7LBqdlE6wJURvqBTqkbomO6OMl8I2gMO0rYYP/ylf5e9Ozl0AzMWqzjwrA3brw6CTPWcup8s4GwHnsdisxrQDkE1ltt5P+MluJGKbQ4PDHrINOnUXSL/lcvUHc4i5clAqO7Baff0QCdl/RBxML5/fDB/OHuJpDu3GRXcWloQReu1gw3zuVaT9yA5JZvf4XQy2fnFNZUDbeNlM4L1tt19JOvLTzBPrr/KchxJ3aKW8L9z0dpMQ1sxE77VyJ+Bpg68k9pzBGcZ8XO0kraS1ZuAdP5LyuOnxOusG6vJA+MRSh+3kmeuOsqi0xVlrr89RiuIwFTG2fegDj5+PH6MTOnEJlfKHmK4pEB+NSSfVvmX8JBOlTg6v/HJpiMxGxpdkrvAC6Adb+gm1M6f5eZrPU3R0AFmDQ1me9HVCg2cL3l4lMgn88OUkRy79ipPPajLZ/CpE/+6j3Gau3XuZbg8LbH3Vo72KSeWaqPo9wge2/poeqfPYBvj+GGAR0GihAOJLvOldX1+VMQd6GWpTp16W2hA7XePxOIQkI=
#  on:
#    tags: true
#    all_branches: true
#    repo: phlummox/hup
#    condition: $RELEASE = true
